[mypy]
python_version = 3.11
warn_unused_configs = True
show_error_codes = True
ignore_missing_imports = True
exclude = (tests|frontend|auth-servis)
files = src/python/utils/document_analyzer, src/python/schemas
strict = True

