services:
  auth-for-check-app:
    image: dipsomask/auth-for-check-app:latest
    ports:
      - "3333:3333"
    networks:
      - auth-for-check-app-network
    container_name: auth-for-check-app

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg-data:/var/lib/postgresql/data
    ports:
      - "65100:5432"
    networks:
      - auth-for-check-app-network
    container_name: postgres


networks:
  auth-for-check-app-network:

volumes:
  pg-data:
