CREATE DATABASE authdb;

\c authdb

-- Generated by the database client.
CREATE TABLE users(
    user_id varchar(250) NOT NULL,
    username varchar(100) NOT NULL,
    password_hash varchar(255) NOT NULL,
    access_token varchar(250),
    refresh_token varchar(250),
    PRIMARY KEY(user_id)
);
CREATE UNIQUE INDEX users_username_key ON users USING btree ("username");
CREATE INDEX id_1742824147650_index ON users USING btree ("user_id");
CREATE UNIQUE INDEX username_unique ON users USING btree ("username");
CREATE UNIQUE INDEX user_id_unique ON users USING btree ("user_id");
