name: Integration of App and Auth servis

on:
  push:
    branches: [ "feature/9-issue" ]
  pull_request:
    branches: [ "feature/9-issue" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout feature/9-issue branch
      uses: actions/checkout@v4
      with:
        ref: 'feature/9-issue'

    - name: Checkout main branch for tests
      uses: actions/checkout@v4
      with:
        path: 'main-branch'
        ref: 'main'

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Copy tests from main branch
      run: |
        cp -r main-branch/tests tests

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      working-directory: ${{ github.workspace }}/tests
      run: |
        pytest
